config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"

  get 'chinese' => 'pages#chinese'
  get 'now' => 'pages#now'
  get 'xmas' => 'pages#xmas'
    get 'xmas_q1' => 'pages#xmas_q1'
    get 'xmas_q2' => 'pages#xmas_q2'
    get 'xmas_q3' => 'pages#xmas_q3'
    get 'xmas_q4' => 'pages#xmas_q4'
    get 'xmas_q5' => 'pages#xmas_q5'
    get 'xmas_q6' => 'pages#xmas_q6'
    get 'xmas_q7' => 'pages#xmas_q7'
    get 'xmas_q8' => 'pages#xmas_q8'
    get 'xmas_q9' => 'pages#xmas_q9'
    get 'xmas_q10' => 'pages#xmas_q10'
    get 'password' => 'pages#password'    

  get 'candidasa' => 'pages#candidasa'
    get 'chakras' => 'pages#chakras'
    get 'stones' => 'pages#stones'
    get 'present' => 'pages#present'

  get 'blockchain' => 'pages#blockchain'

  get 'concepts/index'

  get 'posts/index'

  resources :posts

  get '*path' => redirect('/')

end

app/models/post.rb
class Post < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: :slugged
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def chinese
  end

  def xmas
  end

  def candidasa
  end

  def now
  end

  def blockchain
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all.order("created_at desc").paginate(page: params[:page], per_page: 8)
  end

  def new
  	@post = Post.new
  end

  def create
  	@post = Post.new post_params

  	if @post.save
  		redirect_to @post, notice: "Post was successfully saved"
  	else
  		render 'new', notice: "Unable to save post"
    end
  end

  def show
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: "Post was successfully saved"
    else
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def post_params
  	params.require(:post).permit(:title, :description, :content, :slug)
  end

  def find_post
    @post = Post.friendly.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

	class HTMLwithPygments < Redcarpet::Render::HTML
		def block_code(code, language)
			Pygments.highlight(code, lexer: language)
		end
	end
	def markdown(content)
		renderer = HTMLwithPygments.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer, options).render(content).html_safe
	end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/pages/_home_hero.html.erb
<div class="hero-container">

	<%= render 'pages_header' %>

	<div class="hero-content">
		<%= image_tag "ryan-face.jpg", class: "hero-pic" %>
		<h1>Ryan Crocombe</h1>
	</div>	

	<div class="location">
		<i class="fa fa-map-marker fa-lg" aria-hidden="true"></i>
		<h6>Currently based in</h6>
		<p>London, United Kingdom</p>	
	</div>

</div>

app/views/pages/_home_longterm.html.erb
<div class="section">
	<h3 class="title">Mission</h3>

	<div class="section-text">
		<p>My ultimate goals lie in replacing existing education systems provided by government with a new type of outstanding education.</p>

		<p>I see a values-driven education system as the best way to solve many of the most pressing issues facing the developed and developing worlds, including income inequality, environmental sustainability and the pursuit of happiness.</p>
	</div>
</div>

<hr>

app/views/pages/_home_subscribe.html.erb
<div class="section">
	<h3 class="title dark">Newsletter</h3>

	<div class="section-text subscribe-container">

		<!-- Begin MailChimp Signup Form -->
		<div class="subscribe-container"id="mc_embed_signup">
			<form action="https://ryancrocombe.us14.list-manage.com/subscribe/post?u=8a6f5b1c83bcc558fe30d75af&amp;id=3a0a5d8b5e" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>

			    <div id="mc_embed_signup_scroll">
				
				<h4>Sign up for my newest writing and other updates!</h4>
				
				<div class="mc-field-group subscribe-input-field">
					<label for="mce-EMAIL"></label>
					<input class="email-input" placeholder="Email address" type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
				</div>
				
				<div id="mce-responses" class="clear">
					<div class="response" id="mce-error-response" style="display:none"></div>
					<div class="response" id="mce-success-response" style="display:none"></div>
				</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
			    
			    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_8a6f5b1c83bcc558fe30d75af_3a0a5d8b5e" tabindex="-1" value=""></div>
			    
			    <div class="clear"><input type="submit" value="Sign up!" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
			    </div>

			</form>
		</div>

		<!--End mc_embed_signup-->

	</div>

</div>

<br><br>

app/views/pages/_pages_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RC", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Learn Chinese", chinese_path %></li>
        <% if user_signed_in? %> 
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/pages/blockchain.html.erb
<div class="blockchain-container">

	<h1>Blockchain Home</h1>

	<h2>Concept</h2>

	<p>Hello</p>
		
	<h5>Key Resources</h5>
	<ul>
		<li><%= link_to "Beyond the Bitcoin bubble, New York Times, 1/16/2018", "https://www.nytimes.com/2018/01/16/magazine/beyond-the-bitcoin-bubble.html", target: "_blank", class: "a2" %></li>
	</ul>


	<h2>Technology</h2>



	<h2>Valuation</h2>



	<h2>Tokens</h2>


	<h2>Glossary</h2>


	<h5>Key Resources</h5>
	<ul>
		<li><%= link_to "The Reason Bitcoin & Ethereum are surging, Naval Ravikant, 2/6/2017", "https://blog.producthunt.com/the-reason-bitcoin-ethereum-are-surging-33665c52d7a9", target: "_blank", class: "a2" %></li>
		<li><%= link_to "Thoughts on tokens, Balaji S Ravikant, 1/16/2018", "https://blog.producthunt.com/the-reason-bitcoin-ethereum-are-surging-33665c52d7a9", target: "_blank", class: "a2" %></li>
	</ul>



	<h2>Utilities</h2>
	
		<%= link_to "Slock.it - decentralised Airbnb and other practical applications/hardware driven by smart contracts", "https://slock.it/", target: "_blank", class: "a2" %>


</div>

app/views/pages/home.html.erb
<%= render 'home_hero' %>

<div class="page-content">
	<%= render 'home_intro' %>
	<%= render 'home_writing' %>	
	<%= render 'home_longterm' %>
	<%= render 'home_medterm' %>
	<%= render 'home_daily' %>
	<%= render 'home_background' %>
	<%= render 'home_contact' %>
	<%= render 'home_subscribe' %>		
</div>

<%= render 'pages_footer' %>

<script>
	$( document ).ready(function() {
	  $('[data-toggle="popover"]').popover();
	  $('[data-toggle="collapse"]').collapse();	  
	  $('[data-toggle="tooltip"]').tooltip();	  	  
	});
</script>

app/views/pages/password.html.erb
<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

<div class="xmas-container">


	<div class="section">
		<h1 class="section-title">Solving the password</h1>

		<div class="section-text">
			<p>You should have all of the correct answers now. Follow the following steps to solve the password:</p>
			<br>
			<h3 style="text-decoration:underline;">Step 1</h3>
			<br>
			<p>For each question pair, identify the <em>n</em>th letter of the answer for A, where <em>n</em> is the answer from B.</p>
			<br>
			<h3 style="text-decoration:underline;">Step 2</h3>
			<br>
			<p>Take all of the letters you've identified from Step 1 and you have an anagram of a word. This word is the password. Now all you have to do is unscramble the anagram! You can then log in below.</p>
			<p>Once you're logged in, navigate your way to <em><strong>ryancrocombe.com/xxx</strong></em>, where xxx is the same word as the password.</p>
			<br>
			<p><strong>Hint:</strong> I don't think you'll be able to figure the password out just by looking at the letters. I'll start you off with a clue: <em>it relates to us</em>. I would start by doing some digging and exploring back through our story. Be resourceful and think logically and laterally. If you look in the right place you could find the answer almost immediately.</p>
			<br>
			<p>If you're really struggling then you haven't looked hard enough. But if you insist on sucking out, then I have 3 clues in total that you can ask me for.</p>
		</div>

		<%= link_to "Log in", "users/sign_in", class: "xmas-button-2" %>
		
	</div>

</div>

<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

app/views/pages/present.html.erb
<div class="logged-in-container">
	<div class="xmas-banner-container">
		<div class="xmas-banner">
		</div>
	</div>

	<div class="xmas-container">
		<div class="logged-in">
			<div class="section">
				<% if user_signed_in? %>
					<h1 class="section-title">Merry Christmas!</h1>

					<div class="section-text">
						<p><%= link_to "chakrubs.com", "http://www.chakrubs.com", target: "blank" %></p>
						<p><%= link_to "yoniegg.com", "https://yoniegg.com/", target: "blank" %></p>
						<br><br>
						<p>* * *</p>
						<br><br>
						<p>Once you've decided which one you like most, here are my credit card details. Don't worry about cost, just get whichever one you feel drawn to. And then have the best time with it.</p>
						<br>
						<p>Card number: 4129 8523 3379 9486</p>
						<p>Security number: I'll give you this in person</p>
						<p>Name on card: MR RYAN K CROCOMBE</p>
						<p>Address: 32 Alverton, Great Linford, Milton Keynes, Bucks, MK14 5EF</p>
					</div>

					<br>
					<br>
				
				<% else %>
					<h1 class="section-title">Access denied</h1>

					<div class="section-text">
						<p>You need to be logged in to view this page</p>
					</div>		
				<% end %>
			</div>
		</div>
	</div>

	<div class="xmas-banner-container">
		<div class="xmas-banner">
		</div>
	</div>
</div>

app/views/pages/xmas_q1.html.erb
<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

<div class="xmas-container">


	<div class="section">
		<h1 class="section-title">Question pair 1</h1>

		<div class="section-text">
			<p>A) What is the literal translation into English of my mum’s maiden name?</p>
			<br>
			<p>B) How many lots of red would you find in my favourite Ghanian dish? Add this number to the number of letters in the name of the dish.</p>
		</div>

		<%= link_to "Question 2", "xmas_q2", class: "xmas-button-2" %>
		
	</div>

</div>

<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

app/views/pages/xmas_q10.html.erb
<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

<div class="xmas-container">


	<div class="section">
		<h1 class="section-title">Go hunting!</h1>

		<div class="section-text">
			<p>Now go and find out the answers! Once you've got all 18, make your way to <em><strong>ryancrocombe.com/password</strong></em></p>
			<p>No skipping ahead!</p>
		</div>
		
	</div>

</div>

<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

app/views/pages/xmas_q7.html.erb
<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

<div class="xmas-container">


	<div class="section">
		<h1 class="section-title">Question pair 7</h1>

		<div class="section-text">
			<p>A) What island group in the Pacific did the man that Max was named after live in?</p>
			<br>
			<p>B) My dad’s dad spent time as a professor at a university in the US that is usually referred to by its acronym. Take the number of letters in this acronym and double it.</p>
		</div>

		<%= link_to "Question 8", "xmas_q8", class: "xmas-button-2" %>
		
	</div>

</div>

<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

app/views/pages/xmas_q8.html.erb
<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

<div class="xmas-container">


	<div class="section">
		<h1 class="section-title">Question pair 8</h1>

		<div class="section-text">
			<p>A) Which city in South America did my mum travel to as an 18 year old?</p>
			<br>
			<p>B) My dad and Max have the same middle name. Take the number of letters of their middle name, minus 1 and divide by the number of middle names that Dom has.</p>
		</div>

		<%= link_to "Question 9", "xmas_q9", class: "xmas-button" %>
		
	</div>

</div>

<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

app/views/pages/xmas_q9.html.erb
<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

<div class="xmas-container">


	<div class="section">
		<h1 class="section-title">Question pair 9</h1>

		<div class="section-text">
			<p>A) In which country did I say my first word?</p>
			<br>
			<p>B) How many female cousins do I have?</p>
		</div>

		<%= link_to "Question 10", "xmas_q10", class: "xmas-button-2" %>
		
	</div>

</div>

<div class="xmas-banner-container">
	<div class="xmas-banner">
	</div>
</div>

app/views/posts/_disqus.html.erb
<div class="disqus-container">
	<div id="disqus_thread"></div>
	<script>

	/**
	*  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
	*  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
	/*
	var disqus_config = function () {
	this.page.url = PAGE_URL;  // Replace PAGE_URL with your page's canonical URL variable
	this.page.identifier = PAGE_IDENTIFIER; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
	};
	*/

	var disqus_shortname = 'ryancrocombe';
	var disqus_identifier = '<%= @post.id %>';
	var disqus_title = '<%= @post.title %>';
	var disqus_url = '<%= url_for([@post, {only_path: false}]) %>';

	(function() { // DON'T EDIT BELOW THIS LINE
	var d = document, s = d.createElement('script');
	s.src = '//ryancrocombe.disqus.com/embed.js';
	s.setAttribute('data-timestamp', +new Date());
	(d.head || d.body).appendChild(s);
	})();
	</script>
	<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
</div>

app/views/posts/_posts_footer.html.erb
<footer>
	<p class="purple">&copy; 2018 Ryan Crocombe</p>

	<nav>
		<a href="https://www.medium.com/@ryancrocombe" target="_blank"><i class="fa fa-medium a2"></i></a>
		<a href="https://cn.linkedin.com/in/ryancrocombe" target="_blank"><i class="fa fa-linkedin a2"></i></a>
		<a href="https://www.instagram.com/__ryanryan/" target="_blank"><i class="fa fa-instagram a2"></i></a>
	</nav>

</footer>

app/views/posts/_posts_form.html.erb
<div class="posts-form">

	<%= form_for @post do |f| %>

		<% if @post.errors.any? %>
			<h2><%= pluralize(@post.errors.count, "error") %> prevented this post from saving:</h2>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		<% end %>

		<h5><%= f.label :title %></h5>
		<%= f.text_field :title %>

		<br>
		<br>

		<h5><%= f.label :description %></h5>
		<%= f.text_area :description %>

		<br>
		<br>

		<h5><%= f.label :content, "Write your article here" %></h5>
		<%= f.text_area :content %>

		<br>
		<br>

		<%= f.submit %>

	<% end %>

</div>

app/views/posts/_posts_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "RC", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Blog", posts_path %></li>
        <li><%= link_to "Learn Chinese", chinese_path %></li>
        <% if user_signed_in? %>
          <li>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/posts/_posts_subscribeform.html.erb
<!-- Begin MailChimp Signup Form -->
<div class="subscribe-container"id="mc_embed_signup">
	<form action="https://ryancrocombe.us14.list-manage.com/subscribe/post?u=8a6f5b1c83bcc558fe30d75af&amp;id=3a0a5d8b5e" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>

	    <div id="mc_embed_signup_scroll">
		
		<h3>Sign up for my newest writing and other updates!</h3>
		
		<div class="mc-field-group subscribe-input-field">
			<label for="mce-EMAIL"></label>
			<input class="email-input" placeholder="Email address" type="email" value="" name="EMAIL" class="required email" id="mce-EMAIL">
		</div>
		
		<div id="mce-responses" class="clear">
			<div class="response" id="mce-error-response" style="display:none"></div>
			<div class="response" id="mce-success-response" style="display:none"></div>
		</div>    <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
	    
	    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_8a6f5b1c83bcc558fe30d75af_3a0a5d8b5e" tabindex="-1" value=""></div>
	    
	    <div class="clear subscribe-input-field"><input type="submit" value="Sign up!" name="subscribe" id="mc-embedded-subscribe" class="button"></div>
	    </div>
	
	</form>
</div>

<!--End mc_embed_signup-->

app/views/posts/edit.html.erb
<%= render 'posts_header' %>

<div class="posts-container">

	<h3 class="title">Edit post</h3>
	<div class="posts-content">
		<%= render 'posts_form' %>
	</div>
</div>

<%= render 'posts_footer' %>

app/views/posts/index.html.erb
<%= render 'posts_header' %>

<div class="posts-container">

	<div class="title">
		<h3>Articles</h3>
	</div>

	<% @posts.each do |post| %>
		<div class="post">
			<h6 class="date"><%= post.created_at.strftime("%A, %d %B %Y") %></h6>
			<h2><%= link_to post.title, post %></h2>
			<p><%= post.description %></p>
		</div>

		<hr>	
	<% end %>

	<%= render 'posts_subscribeform' %>

	<div class="pagination">
		<%= will_paginate @posts %>
	</div>


</div>

<%= render 'posts_footer' %>

app/views/posts/new.html.erb
<%= render 'posts_header' %>

<div class="posts-container">

	<h3 class="title">New post</h3>
	<div class="posts-content">
		<%= render 'posts_form' %>
	</div>
</div>

<%= render 'posts_footer' %>

app/views/posts/show.html.erb
<%= render 'posts_header' %>

<div class="posts-container">

	<div class="posts-content">
		<h1><%= @post.title %></h1>
		<div class="date">
			<%= @post.created_at.strftime("%A, %d %B %Y") %>
		</div>
		
		<br>
	
		<%= markdown @post.content %>
	</div>

	<br>

	<% if user_signed_in? %>
		<p><%= link_to "Edit", edit_post_path(@post), class: "purple" %> | <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class: "purple" %></p>
	<% end %>

	<hr>

	<div class="share-box">
		<h6>Share <em><%= @post.title %></em></h6>
		<a href="http://twitter.com/share?text=<%= @post.title %> by @ryancrocombe" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;">
			<i class="fa fa-twitter" aria-hidden="true"></i>
		</a>
		<a href="http://www.facebook.com/sharer.php" onclick="javascript:window.open(this.href,'', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=300,width=600');return false;">
			<i class="fa fa-facebook" aria-hidden="true"></i>
		</a>
	</div>

	<hr>

	<%= render 'disqus' %>	

	<%= render 'posts_subscribeform' %>                        

</div>

<%= render 'posts_footer' %>